spring.application.name=operationshub-ticketing

spring.data.mongodb.uri=mongodb+srv://hirunidesilvaa:PaF1001@cluster0.3vnx6ic.mongodb.net/smart_campus_ops?retryWrites=true&w=majority

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB

app.upload.dir=uploads
